[build]
    command = "quasar build"
    functions = "functions/"
    publish = "dist/spa"

[dev]
    framework = "quasar"
    port = 8888

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
